### ISSUE TITLE
Issue with Ionic Species Recognition in ReacNetGenerator

### ISSUE THREAD

**Issue by SchrodingersCattt** [deepmodeling/reacnetgenerator#2307]
Dear Developer,

I highly appreciate your contribution to species and reactions analysis based on MD trajectories. Recently, I've encountered a problem with ionic species recognition.

While working on ammonium perchlorate, I experienced errors indicating issues with valence on nitrogen atoms. ​The software does not seem to recognize basic ionic species such as perchlorate and ammonium ions correctly.​ Here is the error message received:

`[15:28:29] Explicit valence for atom # 4 N, 4, is greater than permitted`

Additionally, the recognized species output was incorrect, for example:
```
Timestep 11000: H4C0N1O0Cl0_unknownSMILES_0 576 [O][Cl] 576 [O] 1728
Timestep 12000: H4C0N1O0Cl0_unknownSMILES_0 576 [O][Cl] 576 [O] 1728
Timestep 13000: H4C0N1O0Cl0_unknownSMILES_0 576 [O][Cl] 576 [O] 1728
Timestep 14000: H4C0N1O0Cl0_unknownSMILES_0 576 [O][Cl] 576 [O] 1728
```

The attachment is a reproducible case, in which I conducted analysis with command `reacnetgenerator -i dump_nvt_freq-1000.lammpstrj --type dump -a H C N O Cl --nohmm`.

[ap_issue.zip](https://github.com/user-attachments/files/17968155/ap_issue.zip)

Additionally, I am interested in contributing to the improvement of ReacNetGenerator. Could you please provide guidance on how this issue can be addressed or suggest how I might assist in resolving this limitation?

Thank you for your attention to this issue!

Best regards，
M.-Y. Guo

**Comment by njzjz** [comment]
Could you print or raise the error here, so we can know which error was thrown?

https://github.com/deepmodeling/reacnetgenerator/blob/eca9a3902c038883d7329fb17e31c773b7d72fec/reacnetgenerator/_path.py#L416

**Comment by njzjz** [comment]
Probably related to https://github.com/rdkit/rdkit/wiki/FrequentlyAskedQuestions/763a70b70718187ab28197dedd2ffa8392c8fff8

**Comment by SchrodingersCattt** [comment]
Thank you for your prompt response. The printed error is traced back as follows:
```
Maximum BFS search size exceeded. Traceback (most recent call last):
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/_path.py", line 415, in smiles
    self._smiles = self._convertSMILES(self.atoms, self.bonds)
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/_path.py", line 347, in _raise_anyway
    raise ValueError("Maximum BFS search size exceeded.")
ValueError: Maximum BFS search size exceeded.
```


I will try to implement `sanitize=False` to fix this. Right now, I tried to instanitiate with `m = Chem.RWMol(sanitize=False)
` in function  `convertSMILES`, but got error:
```
Traceback (most recent call last):
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/utils.py", line 558, in run_mp
    for item in results:
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/multiprocessing/pool.py", line 423, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7ff37aebee90>'. Reason: 'PicklingError("Can't pickle <class 'Boost.Python.ArgumentError'>: import of module 'Boost.Python' failed")'
Traceback (most recent call last):
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/bin/reacnetgenerator", line 8, in <module>
    sys.exit(_commandline())
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/commandline.py", line 164, in _commandline
    ).runanddraw()
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/reacnetgen.py", line 269, in runanddraw
    self._process(processthing)
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/reacnetgen.py", line 337, in _process
    _CollectPaths.getstype(self).collect()
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/_path.py", line 100, in collect
    self._printmoleculename()
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/_path.py", line 340, in _printmoleculename
    for name, atoms, bonds in results:
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/reacnetgenerator/utils.py", line 558, in run_mp
    for item in results:
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/multiprocessing/pool.py", line 423, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/xxx/Miniconda/envs/deepmd-v2.2.9/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7ff37aebee90>'. Reason: 'PicklingError("Can't pickle <class 'Boost.Python.ArgumentError'>: import of module 'Boost.Python' failed")'
```

**Comment by njzjz** [comment]
> Right now, I tried to instanitiate with `m = Chem.RWMol(sanitize=False) `

I don't think `RWMol` has this argument after I read the documentation https://www.rdkit.org/docs/cppapi/classRDKit_1_1RWMol.html

**Comment by njzjz** [comment]
Fixed in #2322.

**Comment by SchrodingersCattt** [comment]
@njzjz It seems perchlorates still cannot be recognized. It should be ClO4, but I got [O] and [Cl][O]. 

How can I customize bond length to define a fragment? Thanks!
